name: Benchmark

on:
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Download benchmark tool
        run: wget https://github.com/sharkdp/hyperfine/releases/download/v1.16.1/hyperfine_1.16.1_amd64.deb
      - name: Install benchmark tool
        run: sudo dpkg -i hyperfine_1.16.1_amd64.deb

      - name: Install jest-swc
        run: cd tests/jest-swc && npm ci
      - name: Install jest-ts-jest
        run: cd tests/jest-ts-jest && npm ci
      - name: Install node-assert
        run: cd tests/node-assert && npm ci
      - name: Install vitest
        run: cd tests/vitest && npm ci

      - name: run benchmark
        run: hyperfine 'cd bun && bun test' 'cd jest-swc && npm run test' 'cd jest-ts-jest && npm run test' 'cd vitest && npm run test' 'cd node-assert && npm run test' 'cd deno && npm run test'
        working-directory: ${{ github.workspace }}/tests
