name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        workspace: ['bun', 'deno', 'jest-ts-jest', 'jest-swc', 'node-assert', 'vitest']

    steps:
      - uses: actions/checkout@v3.5.2

      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          cache: 'npm'
          cache-dependency-path: ${{ github.workspace }}/tests/${{ matrix.workspace }}/package-lock.json
          node-version: '20'

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ github.workspace }}/tests/${{ matrix.workspace }}

      - name: Execute tests
        run: npm test
        working-directory: ${{ github.workspace }}/tests/${{ matrix.workspace }}
